import api from './axios';

export const academyApi = {
  getPublicCourses: (params?: object) => api.get('/academy/public/courses', { params }),
  getCourses: (params?: object) => api.get('/academy/courses', { params }),
  getCourse: (id: string) => api.get(`/academy/courses/${id}`),
  createCourse: (data: object) => api.post('/academy/courses', data),
  updateCourse: (id: string, data: object) => api.put(`/academy/courses/${id}`, data),
  deleteCourse: (id: string) => api.delete(`/academy/courses/${id}`),
  createModule: (courseId: string, data: object) => api.post(`/academy/courses/${courseId}/modules`, data),
  updateModule: (id: string, data: object) => api.put(`/academy/modules/${id}`, data),
  deleteModule: (id: string) => api.delete(`/academy/modules/${id}`),
  createLesson: (moduleId: string, data: object) => api.post(`/academy/modules/${moduleId}/lessons`, data),
  updateLesson: (id: string, data: object) => api.put(`/academy/lessons/${id}`, data),
  deleteLesson: (id: string) => api.delete(`/academy/lessons/${id}`),
  getCohorts: (params?: object) => api.get('/academy/cohorts', { params }),
  createCohort: (data: object) => api.post('/academy/cohorts', data),
  updateCohort: (id: string, data: object) => api.put(`/academy/cohorts/${id}`, data),
  deleteCohort: (id: string) => api.delete(`/academy/cohorts/${id}`),
  getSchedules: (cohortId: string) => api.get(`/academy/cohorts/${cohortId}/schedules`),
  createSchedule: (cohortId: string, data: object) => api.post(`/academy/cohorts/${cohortId}/schedules`, data),
  updateSchedule: (id: string, data: object) => api.put(`/academy/schedules/${id}`, data),
  deleteSchedule: (id: string) => api.delete(`/academy/schedules/${id}`),
  getAttendance: (params?: object) => api.get('/academy/attendance', { params }),
  recordAttendance: (data: object) => api.post('/academy/attendance', data),
  getAttendanceReport: (cohortId: string) => api.get(`/academy/attendance/report/${cohortId}`),
  createAssessment: (moduleId: string, data: object) => api.post(`/academy/modules/${moduleId}/assessments`, data),
  getAssessmentsByModule: (moduleId: string) => api.get(`/academy/modules/${moduleId}/assessments`),
  getAssessment: (id: string) => api.get(`/academy/assessments/${id}`),
  updateAssessment: (id: string, data: object) => api.put(`/academy/assessments/${id}`, data),
  deleteAssessment: (id: string) => api.delete(`/academy/assessments/${id}`),
  publishAssessment: (id: string, isPublished: boolean) => api.put(`/academy/assessments/${id}/publish`, { isPublished }),
  getSubmissions: (assessmentId: string) => api.get(`/academy/assessments/${assessmentId}/submissions`),
  gradeSubmission: (id: string, data: object) => api.put(`/academy/submissions/${id}/grade`, data),
  // Quiz engine — questions
  createQuestion: (assessmentId: string, data: object) => api.post(`/academy/assessments/${assessmentId}/questions`, data),
  updateQuestion: (id: string, data: object) => api.put(`/academy/questions/${id}`, data),
  deleteQuestion: (id: string) => api.delete(`/academy/questions/${id}`),
  // Certificates
  getCertificates: (params?: object) => api.get('/academy/certificates', { params }),
  issueCertificate: (data: object) => api.post('/academy/certificates/issue', data),
  revokeCertificate: (id: string, reason: string) => api.put(`/academy/certificates/${id}/revoke`, { reason }),
  verifyCertificate: (code: string) => api.get(`/academy/certificates/verify/${code}`),
};
